# Site settings
title: PXEBoot
email: tranmanhhoang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Easy to configure and install with a armbian very cheap and fast.
baseurl: "/pxeboot" # the subpath of your site, e.g. /blog/
url: "http://superordinate.github.io/" # the base hostname & protocol for your site
twitter_username: mhtranbn
github_username:  mhtranbn

# Build settings
markdown: kramdown
