- name: PXEBoot-Ubuntu
  price: 4.99
  slug: PXEBoot-Ubuntu
  sku: UBT
  image: https://lh5.googleusercontent.com/-FLD9UUOA9YU/Vi9Tn4fBDJI/AAAAAAAAQlQ/qqQnZrEjCik/w868-h614-no/Ubuntu_pxe.png

- name: PXEBoot-Debian
  price: 3.99
  slug: PXEBoot-Debian
  sku: DE
  image: https://lh6.googleusercontent.com/-dKTYBVdntck/VjCIr-3u7cI/AAAAAAAAQm8/WSita36tJF8/w300-h395-no/Debian_pxe.png

- name: PXEBoot-RancherOS
  price: 2.99
  slug: PXEBoot-RancherOS
  sku: ROS
  image: https://lh3.googleusercontent.com/-1pgWd4H9oB0/Vi9Tn9eKa9I/AAAAAAAAQlE/x_AQP6WELa0/w1000-h600-no/Rancher_pxe.png
